### ISSUE TITLE
Cannot run and build image

### ISSUE THREAD

**Issue by Alberts00** [mozilla-iot/gateway-docker#5] opened 2018-05-19 23:12 UTC
Hello,
I'm quite new to Mozilla IoT gateway and was working on getting a testing environment working in Docker by following the instructions provided in this repository and stumbled upon an issue, where it appears that the image provided in Docker Hub is outdated since it was trying to access /home/pi` folder.
Full steps on how to arrived at the issue can be seen in this [gist](https://gist.github.com/Alberts00/7ef267dc8146fc5173a292a4d6513df8#file-run-error).

Since Docker Hub image was failing I tried build the image myself and arrived with an issue where yarn did not have executable permissions. Full gist can be seen [here](https://gist.github.com/Alberts00/7ef267dc8146fc5173a292a4d6513df8#file-build-error).

I'm running this on x86 Ubuntu 16.04 server with Docker 18.03.1-ce.

**Comment by mrstegeman** [comment] 2018-05-21 12:41
@Alberts00 Thank you for the bug report!

Let me address some of the individual issues I saw:
1. Errors from `./tools/post-upgrade.sh`, e.g. lines 7-55 of `run error`: This script should not even be running. See https://github.com/mozilla-iot/gateway/pull/1023
2. `/home/pi` errors: will commit a fix shortly.
3. `yarn: Permission denied`: I was unable to reproduce this issue. Maybe a function of the fixes I already have in place?

**Comment by mrstegeman** [comment] 2018-05-21 20:25
@Alberts00 I've got the fixes merged in. Would you mind trying to build again and see if things are fixed? I've not yet updated the image on Docker Hub.

**Comment by mrstegeman** [comment] 2018-05-23 13:44
Glad to hear it. I'll probably wait to push a new image to Docker Hub until our next release.

**Closed by mrstegeman** 2018-05-23 13:44 UTC
Labels: in progress

**Comment by mrstegeman** [comment] 2018-05-25 17:16
@Alberts00 I actually just encountered the `yarn` issue. Fixed with: https://github.com/mozilla-iot/gateway-docker/commit/009d5388db37491d75b50de8208c6e89a7c3f7a0
