### ISSUE TITLE
How to configure proxy for adding ZigBee add-on ? 

### ISSUE THREAD

**Issue by hbkoenig** [mozilla-iot/gateway-docker#43] opened 2020-08-03 09:33 UTC
I'm trying to run webthings-gateway on a RPI4 behind a http proxy and cannot access add-ons directly from the internet:

2020-08-03 11:23:50.266 ERROR  : Failed to parse add-on list: { FetchError: request to https://api.mozilla-iot.org:8443/addons?arch=linux-arm&version=0.12.0&node=64&python=2.7%2C3.7 failed, reason: getaddrinfo ENOTFOUND api.mozilla-iot.org api.mozilla-iot.org:8443

and  I cannot find any hint how/where to configure http proxy ?!

**Comment by mrstegeman** [comment] 2020-08-03 15:15
Duplicate of mozilla-iot/gateway#2566

**Closed by mrstegeman** 2020-08-03 15:15 UTC
